Create gas estimation article
MyCryptoHQ/knowledge-base-content pull request #196
Opened 2020-11-17 16:54 UTC by Mrtenz

2020-11-17 16:58 UTC, Mrtenz commented
[ch7251]

2020-11-17 21:17 UTC, jspence425 requested changes

2020-11-17 21:17 UTC, jspence425 commented on troubleshooting/sending/gas-required-exceeds-allowance-or-always-failing-transaction.md
> +This error can occur, usually when you are trying to interact with a contract. It means that MyCrypto could not estimate the gas limit for your transaction. There are multiple causes for this error,
This error can occur, usually when you are trying to interact with a contract. It means that MyCrypto could not estimate the gas limit for your transaction. There are multiple causes for this error, such as:

-change to-

This error can occur when interacting with a contract, and means that MyCrypto could not estimate the gas limit for your transaction.
<break line>
This error can be caused by a few reasons, including:

2020-11-18 08:38 UTC, wtzb approved these changes

2020-11-18 08:38 UTC, merged